### PR TITLE
#72 Ignore generated Patterns class for coveralls

### PR DESCRIPTION
**Pull request by prondzyn**
For issue #72 

Ignoring generated file to omit coveralls error.

Issue and solution found in coveralls maven plugin: https://github.com/trautonen/coveralls-maven-plugin/issues/57

### CODE REVIEW

**Comment by dmarkov** [comment]
@prondzyn Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@pinaf this pull request is for you, please review

**Comment by pinaf** [comment]
@rultor merge

**Comment by prondzyn** [comment]
@yegor256 ping

**Comment by prondzyn** [comment]
@yegor256 ping. Waiting 6 days for you...

**Comment by prondzyn** [comment]
@yegor256 ping. 8 days...

**Comment by prondzyn** [comment]
@yegor256 please confirm this

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@pinaf I added **16 mins** to your account, many thanks for working with the project (57cfe04304708826ef94acf0)! The completion time here was 313 hours and 25 mins.

extra minutes for review comments (c=1)

added +16 to your rating, now it is equal to [+292](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
