### PR TITLE
feat(#211): We can't use XPath 2.0 features

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
The current version of `jcabi-xml` might use only `XPath 1.0` features which creates some problems like this one #211.
I've tried to use `Saxon` library by specifying:
```
net.sf.saxon.TransformerFactoryImpl
net.sf.saxon.xpath.XPathFactoryImpl
```
implementations and it's still doesn't work (it doesn't crash, but produce wrong results). The same conclusion is described [here](https://stackoverflow.com/a/40192708/10423604): we can't use `XPath 1.0` with `java.xml` interface.  The only solution is use `Saxon` specific API directly. Can we add direct support of `Saxon` API? Something like `SaxonDocument`?

Closes: #211

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
Blocks https://github.com/jcabi/jcabi-xml/issues/211

**Comment by yegor256** [comment]
@volodya-lombrozo no need to make a test that _confirms_ a bug. Instead, make a test that fails and then add `@Disabled` to it.

**Comment by volodya-lombrozo** [comment]
@yegor256 To add `@Disabled` I have to add a puzzle for it too. But the problem is that I don't know what to write in the puzzle since I don't know if `jacabi-xml` is going to support direct `Saxon` implementation of `XML` document.

**Comment by yegor256** [comment]
@volodya-lombrozo in either case, making the test the way you made it -- is wrong. This way you send a message to future programmers -- "this is the expected behavior, the test confirms it, don't change it!"

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look one more time, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
