### PR TITLE
#94 fixed NPE when schema location missed

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #94

* added a new unit test
* fixed NPE when the schemaLocation element missed in the input XML

### CODE REVIEW

**Comment by dmarkov** [comment]
@dmzaytsev Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@carlosmiranda please review this one

**Comment by carlosmiranda** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@carlosmiranda thanks, paid, **16 mins** to your account, payment ID is `73992102`, task took 24 hours to complete. review comments (c=1) added as a bonus. +16 to your rating, your total score is [+2582](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
