### PR TITLE
Comment for xerces dependency

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #74 
Added comment to dependency

### CODE REVIEW

**Comment by dmarkov** [comment]
@amihaiemil I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by amihaiemil** [comment]
@yegor256 Can you merge and close the ticker pls?

**Comment by amihaiemil** [comment]
@yegor256 Don't forget about this one please, it's already so old :D

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@yegor256 I started getting a similar error on travis with other build, maybe something is wrong with maven central repo:-??

**Comment by amihaiemil** [comment]
@yegor256 can you try to merge again?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **17 mins** to your account, payment ID is `000-3196bda1`, task took 1846 hours and 33 mins to complete; review comments (c=2) added as a bonus; +17 to your rating, your total score is [+104](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
