### PR TITLE
ClasspathInput#getStringData() uses default encoding type

### PR DESCRIPTION
**Pull request by piddubnyi**
Solving #98 
Added explicit encoding type.

### CODE REVIEW

**Comment by dmarkov** [comment]
@piddubnyi Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-9d653f88`, task took 122 hours and 6 mins to complete. extra minutes for review comments (c=1). added +16 to your rating, now it is equal to [+3096](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
