### PR TITLE
issue #61

### PR DESCRIPTION
**Pull request by tmjee**
Issue #61 Get Rid of AspectJ

### CODE REVIEW

**Comment by dmarkov** [comment]
@tmjee Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@longtimeago this pull request is for you, please review

**Comment by longtimeago** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@longtimeago Much appreciated! **16 mins** was added to your account, payment ID `67438297`, time spent is 48 hours and 9 mins

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+2485](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
