### PR TITLE
feat(#213): Add SaxonDocument to enable XPath 2.0 features

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add the `SaxonDocument` implementation of `XML` interface to enable `XPath 2.0` features.

Closes: #213

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@volodya-lombrozo maybe you can add a short explanation to `XML.java` javadoc block: why and when should users use `XMLDocument` and when `SaxonDocument`?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you release a new version, please?

**Pull request merged**
