### PR TITLE
modified .gitignore with more files

### PR DESCRIPTION
**Pull request by simonjenga**
modified .gitignore with more files

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@yegor256 **16 mins** added to your account (payment number `000-37736261`), many thanks for your contribution! 20 hours and 46 mins spent here.... extra minutes for review comments (c=1)... +16 added to your rating, at the moment it is: [+7735](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
