### PR TITLE
Fixed failing tests and removed puzzle

### PR DESCRIPTION
**Pull request by amihaiemil**
This PR is for issue #115 . Problem was that the .xsd was moved from address
http://maven.apache.org/maven-v4_0_0.xsd to address http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd .

### CODE REVIEW

**Comment by dmarkov** [comment]
@amihaiemil Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@original-brownbear please review this one

**Comment by original-brownbear** [comment]
@amihaiemil I'm on it :)

**Comment by original-brownbear** [comment]
@amihaiemil all good as far as I can see :)
I guess this should have been an architect review to begin with there is almost nothing to do here.

**Comment by original-brownbear** [comment]
@rultor merge please :)

**Comment by amihaiemil** [comment]
@yegor256 Can you merge this is it's ok? Thanks.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by amihaiemil** [comment]
@yegor256 The merged build passed, but then the master build failed because there is a test failure. However, this has nothing to do with my changes. Should I do something about it? 
image

**Comment by amihaiemil** [comment]
@yegor256 Actually, from what I see in the code, it's simply because threads didn't finish execution before timeour.. I guess it's not the first time this test fails.

**Comment by yegor256** [comment]
@amihaiemil submit a bug about it. maybe the test is not really stable

**Comment by amihaiemil** [comment]
@yegor256 I created ticket #120 .

**Comment by original-brownbear** [comment]
@rultor deploy please.

**Comment by amihaiemil** [comment]
@yegor256 Can you confirm the deploy pls? Thanks.

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by dmarkov** [comment]
@original-brownbear Much appreciated! **19 mins** was added to your account, payment ID `AP-4MU51889VY359963S`, time spent is 48 hours and 4 mins; you're getting extra minutes here (c=4); +19 added to your rating, at the moment it is: [+2579](http://www.netbout.com/b/36646?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
