### PR TITLE
Removed useless variable

### PR DESCRIPTION
**Pull request by amihaiemil**
This concerns issue #96 . Removed useless variable.

### CODE REVIEW

**Comment by dmarkov** [comment]
@amihaiemil Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@yegor256 the PR is rather short, please review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by simonjenga** [comment]
@amihaiemil All Lines Of Code (LOC) that are less than 80 characters long do not need to be broken down into a new line. They should appear as a line on their own.

The ```return``` statement in this method is one such line that is ```<80``` characters long and therefore should be on a single line.

Please always try to always do a CR too.

**Comment by amihaiemil** [comment]
@simonjenga I know the lines can be 80 chars long, but I'm pretty sure qulice complains if you have an unclosed bracked that is not the last character on the line, no? I think that how it is now is the most readable. Should I make another PR for this?

**Comment by simonjenga** [comment]
@amihaiemil This issue has just been tagged as ```CR``` so, please make these two small adjustments to the code in a new PR:

```
final InputStream stream = getClass().getResourceAsStream(
	this.systemid
);
```
and also:

```return IOUtils.toString(stream, Charset.forName("UTF-8"));```

**Comment by amihaiemil** [comment]
@simonjenga done in #117

**Comment by amihaiemil** [comment]
@dmarkov This PR can be deployed. Thanks.

**Comment by simonjenga** [comment]
@amihaiemil :thumbsup: :ok:

**Comment by dmarkov** [comment]
> @dmarkov This PR can be deployed. Thanks.

@amihaiemil sure, no problem

**Comment by dmarkov** [comment]
@yegor256 Thanks so much! Your account was topped up for **16 mins** (transaction ID is `000-e43348ad`, the task took 23 hours and 4 mins); extra minutes for review comments (c=1); +16 added to your rating, at the moment it is: [+1696](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
