### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 **16 mins** added to your account (payment number `000-ead0e0a3`), many thanks for your contribution! 18 hours and 26 mins spent here.. extra minutes for review comments (c=1). +16 added to your rating, at the moment it is: [+4319](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
