### PR TITLE
#47 used system-independent approach to build strings

### PR DESCRIPTION
**Pull request by apocarteres**

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@krzyk it's yours, please review

**Comment by krzyk** [comment]
@apocarteres this PR contains commits from other people, it's hard to read. Please create another clean PR.

**Comment by apocarteres** [comment]
@krzyk seems that github doesn't allow PR the same changes. Can u review only last two commits regarding to #47 issue?

**Comment by krzyk** [comment]
@apocarteres But I would be afraid to merge this PR with all those other changes. Maybe github will allow it when you close this PR, remove the branch and recreate them from a diff?

**Comment by apocarteres** [comment]
let me try

**Comment by apocarteres** [comment]
@krzyk please take a look at correct PR https://github.com/jcabi/jcabi-xml/pull/51

**Comment by apocarteres** [comment]
@dmarkov closed PR as invalid. new corrected is PR #51

**Comment by dmarkov** [comment]
@krzyk I added **16 mins** to your account, many thanks for working with the project!... +16 added to your rating, current score is: [+2879](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
