### PR TITLE
fix(#185): remove synchronization in XSLDocument

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #185

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please approve

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.1`

**Pull request merged**
