### PR TITLE
Preserve DOM structure of XML document when navigating by xpath.

### PR DESCRIPTION
**Pull request by skapral**
Fix for https://github.com/jcabi/jcabi-xml/issues/131.

### CODE REVIEW

**Comment by dmarkov** [comment]
@skapral Thanks for your pull request, let me find someone who can review it

**Comment by skapral** [comment]
Any feedback?

**Comment by skapral** [comment]
Closing this PR as not actual anymore. New PR is https://github.com/jcabi/jcabi-xml/pull/136.

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-xml#132` was not in scope

**Pull request closed without merging**
