### PR TITLE
Update XSLDocument.java

### PR DESCRIPTION
**Pull request by imrandurranee**
Added method to set custom error listener

### CODE REVIEW

**Comment by dmarkov** [comment]
@imrandurranee Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by imrandurranee** [comment]
did anyone get the chance to review it?
Date: Mon, 23 Nov 2015 02:14:51 -0800

**Comment by yegor256** [comment]
@imrandurranee thanks for your pull request, but we're against setters and getters, here is why: http://www.yegor256.com/2014/09/16/getters-and-setters-are-evil.html If you want to have an ability to encapsulate a different error listener, provide it in a constructor

**Comment by dmarkov** [comment]
@yegor256 thank you, added **16 mins** to your acc, payment num is `000-c6e96898`, 70 hours and 45 mins spent in total to complete

extra minutes for review comments (c=1)

+16 added to your rating, current score is: [+9315](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
